### ISSUE TITLE
Cannot Add Users from Web Interface

### ISSUE THREAD

**Issue by remingtonc** [dropbox/nsot#267]
Spun up an instance of NSOT via Docker and manually - in both cases I cannot add users to NSOT after it is provisioned and the superuser has been created.

Order of commands:
```bash
Start NSOT docker image. Entry point is: nsot-server --config=/etc/nsot/nsot.conf.py
docker exec -it nsot-dev bash
nsot-server --config=/etc/nsot/nsot.conf.py createsuperuser --email remcampb@cisco.com
Login and attempt to create users. Hangs with loading spinner.
nsot-server init
Still cannot create users.
nsot-server upgrade
Still cannot create users.
```

Is NSOT fully functional?

**Comment by jathanism** [comment]
Hi there. NSoT is fully functional, but the web interface is lagging behind in feature development. Sorry about the confusion. The `/users` landing page currently does nothing! :(

For now you can use the built-in Django admin dashboard to manually add users found at the `/admin` URL (e.g. http://localhost:8990/admin).

Otherwise, if you're using NSoT with an authenticating proxy that is setting the authenticating header with the email of the incoming user, that user will automatically be created in NSoT. See: http://nsot.readthedocs.io/en/latest/api/rest.html#user-authentication-header

**Comment by jathanism** [comment]
Taking this as a note to fix the documentation to include something about this...

**Comment by jathanism** [comment]
This is also a bug, because the `/users` page shouldn't even exist if it doesn't do anything. It should be comment out until a page is added for it.
